//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOrderingSystem.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodOrder
    {
        public int FoodId { get; set; }
        public int OrderId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Order Order { get; set; }
    }
}
